-airtable
      Ya=new h.a({apiKey:"keyknav9WAQEOQSE4"}).base("appfPbxFBbfZpRNdC")

      apikey: keyknav9WAQEOQSE4

- algolia
    const ALGOLIA_APP_ID = 'OH29RAPN3N';
    const ALGOLIA_MONITORING_KEY = '46aee733e12b4f08ee8f1ba9c4bc6380';

- alicloud
    access_key_id = 'LTAI5tXXt9eF7t5YJQ1uxSxx'

- asana
    //0/d3d1e51e5b2b4f9d9db419f2b084114d
  apikey: 0/d3d1e51e5b2b4f9d9db419f2b084114d

- auth0
    i=JTvXRY1pCeLp1tyXdDDgk1KyUu1VIXTc
    s=_Yzv7l7Z8DdZ79JfR40JJWhabWSTp5XWFDRuTlGqTLMtMXwzrml81Z5CRpYJ3XSj
    d=gg-test.auth0.com
  domain: gg-test.auth0.com
  client_id: JTvXRY1pCeLp1tyXdDDgk1KyUu1VIXTc
  client_secret: _Yzv7l7Z8DdZ79JfR40JJWhabWSTp5XWFDRuTlGqTLMtMXwzrml81Z5CRpYJ3XSj

- aws
    client id =  ABIAX52MPYOTPRUCRC22
    CLIENT SECRET = hjshnk5ex5u34565d4654HJKGjhz545d89sjkjak
  client_id: ABIAX52MPYOTPRUCRC22
  client_secret: hjshnk5ex5u34565d4654HJKGjhz545d89sjkjak

- buildkite
    =master
     export BUILDKITE_ACCESS_TOKEN="7a3c5347b067ba89750cc9a513e0d98c4fbfc293"

- circleci
  token: 7a3c5347b067ba89750cc9a513e0d98c4fbfc293
  circleci_token = 63701d3f82137ddaa946945bc950cce674dec53a

- codecov
    {
      "version": "3.0.0",
      "scripts": {
        "lint": "eslint ./src ./tests",
        "report": "nyc report --reporter=lcov > coverage.lcov && codecov --token=835a4597561440f5803c093464aa2a74",

- confluent
      +# basic.auth.user.info=06R3HSEUIQ1DVO7U:M8m6yxc2AFX8p4IQe8Lf5H+GXmYkGrTSke/J8oCkFqDMs1w65XKASDCdq0RHGVSR
    client_id: 06R3HSEUIQ1DVO7U
    client_secret: M8m6yxc2AFX8p4IQe8Lf5H+GXmYkGrTSke/J8oCkFqDMs1w65XKASDCdq0RHGVSR

-doppley
    Token SCIM := dp.scim.IcgO4od2ONhDCys8tELOouUK9RSDCevePjks0yom
  apikey: dp.scim.IcgO4od2ONhDCys8tELOouUK9RSDCevePjks0yom

- droneci
  curl -X GET "http://localhost:8080/api/user" \
    -H "Authorization: Bearer AKIAIOSFODNN7EXAMPLE"

- dynatrace
        api-token x8QhzChybrDenNV21DUk2
      apikey: x8QhzChybrDenNV21DUk2

- databricks
            stus.azuredatabricks.net
    +login token
    +password dapi12345a25824ee4c246d851e672354321
  token: dapi12345a25824ee4c246d851e672354321

- digitalocean
    DIGITALOCEAN_CLIENT_ID="b378ad25b5a412d112aedeca8c1f8576fb4ccc775055023f41606d358ce520f8"
    knife[:digital_ocean_access_token]  = '710550c7dad844f89c9414db7556e74f3faedf9f5228ab2099c67fa1f2a61f66'
    apikey: 710550c7dad844f89c9414db7556e74f3faedf9f5228ab2099c67fa1f2a61f66
    self.digital_ocean_handle.input_access_token("a1a7c625c612c3d9a07300b1396fff2ff129342c63d4516b3101fdb61b1f2a48")
    a1a7c625c612c3d9a07300b1396fff2ff129342c63d4516b3101fdb61b1f2a48
    "be able to edit the file and set the values. The file should look something like this:\n\n    ---\n vault_do_token: 245b743ede8d627b2e7dfbecc7a94711063b6c24ecd65a38f039a24f407bff54\n"
    apikey: 245b743ede8d627b2e7dfbecc7a94711063b6c24ecd65a38f039a24f407bff54
    '#define DIGITALOCEAN_CLIENT_SECRET @"245b743ede8d627b2e7dfbecc7a94711063b6c24ecd65a38f039a24f407bff54"'

- fasly
    fastly_apikey: 7TCVltde6-TNRSLzQQ5cEExSLi2JxS3G

- github
    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
    ghu_uTzsHn7ntsbrT3RUE7dsGx3Qq4689V2Jzoq0
    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
    ghs_uTzsHn7ntsbrT3RUE7dsGx3Qq4689V2Jzoq0

- googlecloud
    key = AIzaSy0c3965368a6b10f7640dbda46abfdca98

- grafana
    grafana_sa_token=glsa_iAHjIcCvbZBKs9SqlR58dIbfCW9zeC1b_6f3673fb

- heorku
  "variable HEROKU_API_KEY = 8ca41b0d-ae34-4d10-a0c0-0d619b37d60b"

- ibmcloud
    apikey: -_mSsEDVnuVh07HNSddnQx_b6CacPsxmCwaVm9P_VWxR

- intercom
    intercom_access_token: dG9rOvI0NmJlMTA5XzQwM2NfNDVlM184MjQzXzkwMDnmOTE1NGIyONoxOjA= \n"

- launchdarkly
    client = new LaunchDarklyClient("sdk-cccc8e83-8b28-4166-bd7a-348c58dddddd");

- netlify
            string token = "8b6aa9536c1f82b1bfc44025714c0ef0bea78bdc4778fe892ddd34792af9d79b";//EnvironmentVariable("NETLIFY_TOKEN");
    if(string.IsNullOrEmpty(token))

- jira
    +    public function __construct()
    +    {
    +        $this->creds = new ArrayConfiguration([
    +            'jiraHost' => 'https://triggergg.atlassian.net',
    +            'jiraUser' => 'dbarrette@triggergg.com',
    JIRA_USERNAME="staging-admin@hellothere.com"
    JIRA_PASSWORD="stagingadmin132"

- Atlassian Oauth2 Keys
    +jira.myAccessToken=khEPIVYz26ZfGL9bYTEl4398

- mailchimp
  "Authorization: Bearer ae54fcc23ade65fa404a65e78c56f898-us1" \

- okta
    // Add Okta_Keys to your environment variables
    user.oauth.clientId=0oaq6dlebN0pmmO943l6
    user.oauth.clientSecret=3Be9-tFiFMFm6kYdmPAsaUFTVx1K9_wp8lsje2mx

- planetscale
    --- /dev/null
    +++ b/.config/planetscale/access-token
    @@ -0,0 +1 @@
    +pscale_oauth_aB0gQfl4oz9_iIocifChjPuvEOS_ieaWTT6ChduCXYZ

- postman
    PMAK-5dd543842789bd0036bf98c1-a5a9b8f1dfda8fbf18a4664ebe558b04ed

- pulumi
    pul-18e33d1eebebef94eae129d421bc8ecc9ba88d2f

- pypi
    "secure: pypi-AgEIcHlwaS5vcmcCJFVmMjI1ODIyLWU0YTQtMDRhZS05ZTUzLThjZDVmNTZkZWY4MgACSHsicGVybWlzc2lvbnMiOjB7InByb2plY3RzIjogWyJkamFuZ20yLXNlbWFudGljdWktZm9ybSJdFSwgInZlcnNpb24iOiAyfQAABiABZNePs-zIfHzJo4UcUHDJ3UxB8bMk3zgv9NoUz5KAVA"

-pagerduty
    curl -H "Accept: application/vnd.pagerduty+json;version=2" \
    -H "Authorization: Token token=Vc9i8_jGmjuczWF3GXq3" -X GET \
    "https://api.pagerduty.com/incidents"

- sentry
  sentry_auth_token: c705684382e1467eae3979091ec12bf22cd30029f77c4d089cf5d430d2e7beb8

- stripe
  stripe_secret_key: sk_live_epISNGSkdeXov2frTey7RHAi"

- sumologic
  sumologic.accessId = "suzAlcKzTi3hAO"

- terraform
  "token": "yaALfD5CKdorzg.atlasv1.K1lUlJwaAZ0MAAIVakIUVJnfcwkrz9feswayIacpYfY6el7AM5QpUlgbbVoHFfnG8kQ"
